apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: maven
    image: maven:3.5.0
    command:
    - cat
    tty: true
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
#     args: ["--dockerfile=./Dockerfile",
#             --context=`pwd`,
#  #           "--no-push",
#             "--destination=eu.gcr.io/emea-sa-demo/petclinic-kaniko:latest"]
    volumeMounts:
      - name: kaniko-secret
        mountPath: /secret
      # - name: context
      #   mountPath: /context
    env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /secret/kaniko-secret.json
  restartPolicy: Never
  volumes:
    - name: kaniko-secret
      secret:
        secretName: kaniko-secret